//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ControlPanel.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PROPPAGE_ADVANCED           102
#define IDS_TITLE                       102
#define IDD_PROPPAGE_SECURITY           102
#define IDS_MODULEIOPROP                103
#define IDS_NOTSET                      104
#define IDS_NODIR_CREATE                105
#define IDS_IN_OUT_PATH_ERR             106
#define IDD_PROPPAGE_DEBUG              106
#define IDS_COLNAME_TYPE                107
#define IDS_COLNAME_NAME                108
#define IDS_COLNAME_VER                 109
#define IDS_COLNAME_CONFIG              110
#define IDS_STRING_SOCKET               111
#define IDS_STRING_FILE                 112
#define IDS_STRING_PACMODULE            113
#define IDS_STRING_OUTMODULE            113
#define IDS_STRING_CLIENT_MODE          114
#define IDS_STRING_INPORT               115
#define IDS_STRING_OUTPORT              116
#define IDS_STRING_IN_PATH              117
#define IDS_STRING_OUT_PATH             118
#define IDS_STRING_LOG_FILE_FILTER      119
#define IDS_STRING_DOT_TXT              120
#define IDS_STRING_IP_ADDRESS           121
#define IDS_STRING_IN                   122
#define IDS_STRING_OUT                  123
#define IDS_STRING_PORT                 124
#define IDS_STRING_CONFIRM_DEL          125
#define IDS_STRING_CONFIRM_NEWPAC       126
#define IDS_CPL_NAME                    127
#define IDR_MAINFRAME                   128
#define IDS_CPL_INFO                    128
#define IDS_STRING_INMODULE             129
#define IDD_INPUT_CONFIG                130
#define IDD_PROPDLG_SOCKET              132
#define IDD_PROPDLG_FILE                133
#define IDD_PROPPAGE_INPUT              136
#define IDD_PROPPAGE_MAIN               137
#define IDD_NEW_MODULE                  138
#define IDD_CLIENT_CONFIG               140
#define IDC_RADIO_SOCKET                1001
#define IDC_RADIO_FILE                  1002
#define IDC_RADIO_SERIAL                1003
#define IDC_SOCKETNUM                   1005
#define IDC_INPUT_PATH                  1007
#define IDC_OUTPUT_PATH                 1008
#define IDC_CHOOSEPATH_OUT              1010
#define IDC_STATIC_INPUT_PATH           1011
#define IDC_STATIC_OUTPUT_PATH          1012
#define IDC_STATIC_SOCKET_PORT_NUM      1013
#define IDC_PROPERTIES                  1017
#define IDC_TRACE_LEVELS                1019
#define IDC_LOG_FILE                    1020
#define IDC_DISPLAY_NAME                1022
#define IDC_LIST                        1024
#define IDC_ADD                         1025
#define IDC_DEL                         1026
#define IDC_ODBCSTRING                  1026
#define IDC_EDIT                        1027
#define IDC_PROCACCNT                   1027
#define IDC_TABLEACCNT                  1028
#define IDC_DBTYPE                      1029
#define IDC_CHOOSEPATH                  1030
#define IDC_EDIT1_TITLE                 1033
#define IDC_EDIT1                       1034
#define IDC_EDIT2_TITLE                 1035
#define IDC_MONITOREXE                  1035
#define IDC_EDIT2                       1036
#define IDC_EDIT3_TITLE                 1037
#define IDC_EDIT4                       1038
#define IDC_EDIT4_TITLE                 1039
#define IDC_EDIT3                       1040
#define IDC_FRAME                       1041
#define IDC_DBKEYNAME                   1042
#define IDC_MONKEYNAME                  1043
#define IDC_VERSION                     1044
#define IDC_CHOOSEPATH_IN               1045
#define IDC_CLIENT                      1046
#define IDC_CONFIG                      1047
#define IDC_IPADDRESS                   1048
#define IDC_PORT                        1049
#define IDC_MAIN_SS_IP                  3000
#define IDC_BKUP_SS_IP                  3001
#define IDC_MAIN_SS_PORT                3002
#define IDC_BKUP_SS_PORT                3003
#define IDC_SECSERV_TOKEN               3004
#define IDC_IN                          3005
#define IDC_OUT                         3006
#define IDC_CHECK1                      3007
#define IDC_CHECK2                      3008
#define IDC_CHECK3                      3009
#define IDC_CHECK4                      3010
#define IDC_CHECK5                      3011
#define IDC_CHECK6                      3012
#define IDC_CHECK7                      3013
#define IDC_CHECK8                      3014
#define IDC_CHECK9                      3015
#define IDC_CHECK10                     3016
#define IDC_CHECK12                     3017
#define IDC_CHECK13                     3018
#define IDC_CHECK14                     3019
#define IDC_CHECK15                     3020
#define IDC_CHECK11                     3021
#define IDC_CHECK16                     3022
#define IDC_DAILY_LOG                   3024
#define IDC_CHECK_ALL                   3025
#define IDC_CLEAR_ALL                   3026
#define IDC_DEFAULT                     3027

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3000
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         3026
#define _APS_NEXT_SYMED_VALUE           3000
#endif
#endif
